url: "https://hurricanepkt.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/Pi_Display" # the subpath of your site, e.g. /blog
title: Pi Display" # the name of your site, e.g. ACME Corp.
